# Keep Compose / Kotlin metadata.
-dontwarn androidx.compose.**

# Room uses reflection for DAO implementations generated by KSP.
-keep class androidx.room.** { *; }
-keep @androidx.room.Entity class * { *; }
